version: '3.9'
services:
 db:
  image: postgres:13
  environment: 
   - POSTGRES_PASSWORD=example
   - POSTGRES_USER=cristiam
   - POSTGRES_DB=itiVinculacion
  ports:
   - 5432:5432
  volumes:
   - ./postgre_data:/var/lib/postgresql/data
  restart: always
 pgadmin:
  image: dpage/pgadmin4
  environment:
   - PGADMIN_DEFAULT_EMAIL=mail@iti.edu.ec
   - PGADMIN_DEFAULT_PASSWORD=12345
  ports:
   - 5500:80
